/**
 * E2E Black-Box Test: Recording Interaction Noise Fix
 *
 * Validates that internal polling commands (_internal: true) are excluded
 * from session recordings, while user-initiated commands are still recorded.
 *
 * Tests both layers as black boxes:
 *   Layer 1 (MCP tools.ts): checkActionability sends _internal: true
 *   Layer 2 (background.ts): recording interceptor filters _internal commands
 *
 * Since background.ts is an IIFE (not importable), Layer 2 is tested by
 * extracting the exact guard logic and replaying real command sequences.
 */

import { describe, it, expect, vi } from "vitest";
import { checkActionability, pollActionability, ACTIONABILITY_BACKOFF } from "@/mcp-server/tools";

// ============================================================
// Helpers
// ============================================================

/** Capture every command sent through bridge.send */
function createCapturingBridge(response: unknown = { actionable: true }) {
  const captured: Array<{ cmd: any; timeout?: number }> = [];
  return {
    captured,
    bridge: {
      send: vi.fn(async (cmd: any, timeout?: number) => {
        captured.push({ cmd, timeout });
        return response;
      }),
      isConnected: true,
      push: vi.fn(),
    },
  };
}

/**
 * Replicate the EXACT recording guard from background.ts line 2244.
 * This is the single line we changed — test it as a predicate.
 */
function shouldRecord(
  activeRecording: boolean,
  toolInSet: boolean,
  command: Record<string, unknown>,
): boolean {
  // Original (before fix): activeRecording && toolInSet
  // Fixed:                  activeRecording && toolInSet && !command._internal
  return activeRecording && toolInSet && !command._internal;
}

/** The 12 interaction tools from background.ts line 531-536 */
const RECORDING_INTERACTION_TOOLS = new Set([
  "browser_navigate", "browser_click", "browser_type", "browser_press_key",
  "browser_hover", "browser_select_option", "browser_scroll",
  "browser_double_click", "browser_drag", "browser_fill_form",
  "browser_evaluate", "browser_file_upload",
]);

// ============================================================
// Layer 1: checkActionability sends _internal: true
// ============================================================

describe("Layer 1: checkActionability marks commands as internal", () => {
  it("bridge.send receives _internal: true", async () => {
    const { bridge, captured } = createCapturingBridge({ actionable: true });
    await checkActionability(bridge as any, "#btn");

    expect(captured).toHaveLength(1);
    expect(captured[0].cmd._internal).toBe(true);
  });

  it("command type is browser_evaluate", async () => {
    const { bridge, captured } = createCapturingBridge({ actionable: true });
    await checkActionability(bridge as any, "a.link");

    expect(captured[0].cmd.type).toBe("browser_evaluate");
  });

  it("expression field is present and non-empty", async () => {
    const { bridge, captured } = createCapturingBridge({ actionable: true });
    await checkActionability(bridge as any, "div");

    expect(typeof captured[0].cmd.expression).toBe("string");
    expect(captured[0].cmd.expression.length).toBeGreaterThan(0);
  });

  it("selector is embedded in the expression", async () => {
    const { bridge, captured } = createCapturingBridge({ actionable: true });
    await checkActionability(bridge as any, "#my-special-btn");

    expect(captured[0].cmd.expression).toContain("#my-special-btn");
  });

  it("_internal is strictly boolean true, not truthy string", async () => {
    const { bridge, captured } = createCapturingBridge({ actionable: true });
    await checkActionability(bridge as any, "a");

    expect(captured[0].cmd._internal).not.toBe("true");
    expect(captured[0].cmd._internal).toBe(true);
  });
});

// ============================================================
// Layer 1b: pollActionability sends MULTIPLE _internal commands
// ============================================================

describe("Layer 1b: pollActionability generates multiple internal commands", () => {
  it("all retry attempts are marked _internal: true", async () => {
    let callCount = 0;
    const bridge = {
      send: vi.fn(async (cmd: any) => {
        callCount++;
        // Fail first 3, succeed on 4th
        if (callCount < 4) return { actionable: false, reason: "Element not found" };
        return { actionable: true };
      }),
      isConnected: true,
      push: vi.fn(),
    };

    await pollActionability(bridge as any, "#delayed", 5000);

    expect(callCount).toBe(4);
    for (const call of bridge.send.mock.calls) {
      expect(call[0]._internal).toBe(true);
    }
  });

  it("zero user-visible commands are generated by polling", async () => {
    const allCommands: any[] = [];
    const bridge = {
      send: vi.fn(async (cmd: any) => {
        allCommands.push(cmd);
        return { actionable: true };
      }),
      isConnected: true,
      push: vi.fn(),
    };

    await pollActionability(bridge as any, "button", 1000);

    // Every single command must be internal
    const nonInternal = allCommands.filter(c => !c._internal);
    expect(nonInternal).toHaveLength(0);
  });
});

// ============================================================
// Layer 2: Recording guard filters _internal commands
// ============================================================

describe("Layer 2: Recording guard predicate", () => {
  describe("commands that SHOULD be recorded", () => {
    it("browser_click without _internal", () => {
      const cmd = { type: "browser_click", selector: "#btn" };
      expect(shouldRecord(true, RECORDING_INTERACTION_TOOLS.has(cmd.type), cmd)).toBe(true);
    });

    it("browser_evaluate without _internal (user-initiated)", () => {
      const cmd = { type: "browser_evaluate", expression: "document.title" };
      expect(shouldRecord(true, RECORDING_INTERACTION_TOOLS.has(cmd.type), cmd)).toBe(true);
    });

    it("browser_navigate without _internal", () => {
      const cmd = { type: "browser_navigate", url: "https://example.com" };
      expect(shouldRecord(true, RECORDING_INTERACTION_TOOLS.has(cmd.type), cmd)).toBe(true);
    });

    it("browser_type without _internal", () => {
      const cmd = { type: "browser_type", selector: "input", text: "hello" };
      expect(shouldRecord(true, RECORDING_INTERACTION_TOOLS.has(cmd.type), cmd)).toBe(true);
    });

    it("browser_fill_form without _internal", () => {
      const cmd = { type: "browser_fill_form", selector: "form", values: {} };
      expect(shouldRecord(true, RECORDING_INTERACTION_TOOLS.has(cmd.type), cmd)).toBe(true);
    });
  });

  describe("commands that SHOULD NOT be recorded (internal polling)", () => {
    it("browser_evaluate with _internal: true", () => {
      const cmd = { type: "browser_evaluate", _internal: true, expression: "(() => { ... })()" };
      expect(shouldRecord(true, RECORDING_INTERACTION_TOOLS.has(cmd.type), cmd)).toBe(false);
    });

    it("any interaction tool with _internal: true is filtered", () => {
      for (const tool of RECORDING_INTERACTION_TOOLS) {
        const cmd = { type: tool, _internal: true };
        expect(shouldRecord(true, RECORDING_INTERACTION_TOOLS.has(tool), cmd)).toBe(false);
      }
    });
  });

  describe("commands that skip recording (not interaction tools)", () => {
    it("capture_page is not in RECORDING_INTERACTION_TOOLS", () => {
      expect(RECORDING_INTERACTION_TOOLS.has("capture_page")).toBe(false);
      const cmd = { type: "capture_page" };
      expect(shouldRecord(true, false, cmd)).toBe(false);
    });

    it("take_screenshot is not in RECORDING_INTERACTION_TOOLS", () => {
      expect(RECORDING_INTERACTION_TOOLS.has("take_screenshot")).toBe(false);
    });

    it("get_dom_snapshot is not in RECORDING_INTERACTION_TOOLS", () => {
      expect(RECORDING_INTERACTION_TOOLS.has("get_dom_snapshot")).toBe(false);
    });
  });

  describe("no recording active — nothing is recorded", () => {
    it("regular command with no active recording", () => {
      const cmd = { type: "browser_click", selector: "#btn" };
      expect(shouldRecord(false, RECORDING_INTERACTION_TOOLS.has(cmd.type), cmd)).toBe(false);
    });

    it("internal command with no active recording", () => {
      const cmd = { type: "browser_evaluate", _internal: true, expression: "..." };
      expect(shouldRecord(false, RECORDING_INTERACTION_TOOLS.has(cmd.type), cmd)).toBe(false);
    });
  });
});

// ============================================================
// Layer 2b: Edge cases for _internal flag
// ============================================================

describe("Layer 2b: _internal edge cases", () => {
  it("_internal: false does NOT filter (treated as user command)", () => {
    const cmd = { type: "browser_evaluate", _internal: false, expression: "x" };
    // !false === true, so this passes the guard
    expect(shouldRecord(true, true, cmd)).toBe(true);
  });

  it("_internal: undefined does NOT filter (normal user command)", () => {
    const cmd = { type: "browser_evaluate", expression: "x" };
    // !undefined === true
    expect(shouldRecord(true, true, cmd)).toBe(true);
  });

  it("_internal: null does NOT filter (falsy, treated as user command)", () => {
    const cmd = { type: "browser_evaluate", _internal: null, expression: "x" };
    // !null === true
    expect(shouldRecord(true, true, cmd)).toBe(true);
  });

  it("_internal: 0 does NOT filter (falsy number)", () => {
    const cmd = { type: "browser_evaluate", _internal: 0, expression: "x" };
    // !0 === true
    expect(shouldRecord(true, true, cmd)).toBe(true);
  });

  it("_internal: 'true' (string) DOES filter (truthy)", () => {
    const cmd = { type: "browser_evaluate", _internal: "true", expression: "x" };
    // !"true" === false
    expect(shouldRecord(true, true, cmd)).toBe(false);
  });

  it("_internal: 1 DOES filter (truthy number)", () => {
    const cmd = { type: "browser_evaluate", _internal: 1, expression: "x" };
    // !1 === false
    expect(shouldRecord(true, true, cmd)).toBe(false);
  });
});

// ============================================================
// Integration: Simulated smart.click flow
// ============================================================

describe("Integration: Simulated smart.click recording", () => {
  /**
   * Simulate what happens when smart.click("a") is called during a recording.
   * The bridge receives:
   *   1. N × browser_evaluate (_internal: true) — from pollActionability
   *   2. 1 × browser_click (_internal: absent) — the actual click
   *
   * We replay these commands through the recording guard and verify counts.
   */
  it("smart.click generates 1 recorded interaction, not 10+", async () => {
    const allCommands: Array<{ type: string; _internal?: boolean; [k: string]: unknown }> = [];

    // Phase 1: Collect commands from pollActionability
    const bridge = {
      send: vi.fn(async (cmd: any) => {
        allCommands.push({ ...cmd });
        return { actionable: true };
      }),
      isConnected: true,
      push: vi.fn(),
    };

    await pollActionability(bridge as any, "a", 1000);

    // Phase 2: Add the actual browser_click (no _internal flag)
    allCommands.push({ type: "browser_click", selector: "a" });

    // Phase 3: Replay through recording guard
    const recorded: typeof allCommands = [];
    for (const cmd of allCommands) {
      if (shouldRecord(true, RECORDING_INTERACTION_TOOLS.has(cmd.type), cmd)) {
        recorded.push(cmd);
      }
    }

    // Evidence: multiple commands were generated total
    expect(allCommands.length).toBeGreaterThan(1);

    // Evidence: only the actual click was recorded
    expect(recorded).toHaveLength(1);
    expect(recorded[0].type).toBe("browser_click");
    expect(recorded[0]._internal).toBeUndefined();
  });

  it("smart.type generates 1 recorded interaction, not 10+", async () => {
    const allCommands: Array<{ type: string; _internal?: boolean; [k: string]: unknown }> = [];

    const bridge = {
      send: vi.fn(async (cmd: any) => {
        allCommands.push({ ...cmd });
        return { actionable: true };
      }),
      isConnected: true,
      push: vi.fn(),
    };

    await pollActionability(bridge as any, "input#email", 1000);

    // Add the actual browser_type (no _internal flag)
    allCommands.push({ type: "browser_type", selector: "input#email", text: "test@example.com" });

    const recorded = allCommands.filter(cmd =>
      shouldRecord(true, RECORDING_INTERACTION_TOOLS.has(cmd.type), cmd)
    );

    expect(recorded).toHaveLength(1);
    expect(recorded[0].type).toBe("browser_type");
  });

  it("user-initiated browser_evaluate IS still recorded", async () => {
    // User calls execute tool with an expression — no _internal flag
    const userEvaluate = { type: "browser_evaluate", expression: "document.title" };
    expect(shouldRecord(true, RECORDING_INTERACTION_TOOLS.has(userEvaluate.type), userEvaluate)).toBe(true);
  });

  it("10 sequential polling evaluates + 1 click = exactly 1 recording", () => {
    // Simulate worst case: 10 polling retries before click
    const commands: Array<Record<string, unknown>> = [];

    for (let i = 0; i < 10; i++) {
      commands.push({
        type: "browser_evaluate",
        _internal: true,
        expression: `(() => { const el = document.querySelector("a"); ... })()`,
      });
    }
    commands.push({ type: "browser_click", selector: "a" });

    const recorded = commands.filter(cmd =>
      shouldRecord(true, RECORDING_INTERACTION_TOOLS.has(cmd.type as string), cmd)
    );

    expect(commands).toHaveLength(11);
    expect(recorded).toHaveLength(1);
    expect(recorded[0].type).toBe("browser_click");
  });
});

// ============================================================
// Serialization: _internal survives JSON round-trip
// ============================================================

describe("Serialization: _internal survives JSON round-trip", () => {
  it("JSON.stringify preserves _internal: true", () => {
    const cmd = { type: "browser_evaluate", _internal: true, expression: "..." };
    const serialized = JSON.stringify(cmd);
    const deserialized = JSON.parse(serialized);

    expect(deserialized._internal).toBe(true);
    expect(typeof deserialized._internal).toBe("boolean");
  });

  it("JSON.parse of command without _internal has undefined", () => {
    const cmd = { type: "browser_click", selector: "a" };
    const deserialized = JSON.parse(JSON.stringify(cmd));

    expect(deserialized._internal).toBeUndefined();
    // !undefined === true, so guard passes (command is recorded)
    expect(!deserialized._internal).toBe(true);
  });

  it("spread operator preserves _internal in recorded args", () => {
    // background.ts line 2258: const { type: _, id: _id, ...args } = command;
    const command = { type: "browser_evaluate", id: "uuid", _internal: true, expression: "..." };
    const { type: _, id: _id, ...args } = command;

    // _internal leaks into args — but that's fine because the command is filtered
    // before reaching the spread. Verify the spread behavior.
    expect(args._internal).toBe(true);
    expect(args.expression).toBe("...");
  });

  it("filtered internal commands never reach the args spread", () => {
    // Verify: if _internal is true, shouldRecord returns false,
    // so the spread at line 2258 is never reached.
    const command = { type: "browser_evaluate", _internal: true, expression: "..." };
    const wouldRecord = shouldRecord(true, RECORDING_INTERACTION_TOOLS.has(command.type), command);
    expect(wouldRecord).toBe(false);
    // The spread code at line 2258-2267 only executes if shouldRecord is true.
    // So _internal never appears in recorded interaction args.
  });
});

// ============================================================
// ACTIONABILITY_BACKOFF constant verification
// ============================================================

describe("ACTIONABILITY_BACKOFF constant", () => {
  it("is exported and has expected shape", () => {
    expect(Array.isArray(ACTIONABILITY_BACKOFF)).toBe(true);
    expect(ACTIONABILITY_BACKOFF).toEqual([0, 20, 100, 100, 500]);
  });

  it("first attempt has 0ms delay (immediate)", () => {
    expect(ACTIONABILITY_BACKOFF[0]).toBe(0);
  });

  it("worst case: 5+ retries means 5-10 evaluate calls per action", () => {
    // This confirms the noise problem — without the fix, 5+ evals per click
    expect(ACTIONABILITY_BACKOFF.length).toBe(5);
  });
});

// ============================================================
// Failure path: _internal does NOT break command execution
// ============================================================

describe("Failure path: _internal does not break command execution", () => {
  it("checkActionability returns actionable result despite _internal flag", async () => {
    const { bridge } = createCapturingBridge({ actionable: true });
    const result = await checkActionability(bridge as any, "#btn");
    expect(result.actionable).toBe(true);
  });

  it("checkActionability returns non-actionable result despite _internal flag", async () => {
    const { bridge } = createCapturingBridge({ actionable: false, reason: "Element not found" });
    const result = await checkActionability(bridge as any, "#missing");
    expect(result.actionable).toBe(false);
    expect(result.reason).toBe("Element not found");
  });

  it("internal commands still fall through to handleCommand", () => {
    // The guard at line 2244 returns early for recorded commands.
    // If the guard doesn't match (because _internal is true), execution
    // falls through to line 2278: return handleCommand(command);
    // This means internal commands still execute — they just aren't recorded.
    const cmd = { type: "browser_evaluate", _internal: true, expression: "1+1" };
    const wouldRecord = shouldRecord(true, RECORDING_INTERACTION_TOOLS.has(cmd.type), cmd);
    expect(wouldRecord).toBe(false);
    // Falls through to handleCommand — command executes normally
  });
});
